### ISSUE TITLE
App is missing reps

### ISSUE THREAD

**Issue by aaronPMorabito** [Mataco817/OpenBarbell#11]
Some reps are being missed by the application. They are registered by the OpenBarbell device but do not show up on the set card.

**Comment by Mataco817** [comment]
Due to switching from rep JSON objects to an array of floats. Ng Repeat must distinguish between the floats like it can object instances.

Fixed by adding 'track by $index' to the ng repeat expression.

**Comment by Mataco817** [comment]
Fixed
